version: "3.9"

services:
  kwaainet-node:
    image: kwaailab/kwaainet-node:latest
    container_name: kwaainet-node
    restart: unless-stopped
    environment:
    - PUBLIC_NAME=${USER:-kwaainet_user}
    - PUBLIC_IP=${PUBLIC_IP:-}
    - KWAAINET_BLOCKS=4
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache
    ports:
      - "8081:8080"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"


  kwaainet-api:
    image: kwaailab/kwaainet-api:latest
    container_name: kwaainet-api
    restart: unless-stopped
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache:z
    ports:
      - "8000:8000"

