services:
  web:
    container_name: kwaainet-server
    build:
      context: ../../
      dockerfile: docker/kwaainet_server/DockerFile
    image: kwaainet-server
    ports:
      - "8080:8080"
 # Run with GPUs only if available
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Use all GPUs if available, otherwise use CPU